name: parlai
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.11
  - pip=23.2.1
  - python=3.10.13
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - alabaster==0.7.13
      - antlr4-python3-runtime==4.9.3
      - anyascii==0.3.2
      - asttokens==2.4.0
      - async-timeout==4.0.3
      - attrs==20.2.0
      - babel==2.12.1
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - bitarray==2.8.1
      - bs4==0.0.1
      - cachetools==5.3.1
      - certifi==2023.7.22
      - cffi==1.16.0
      - chardet==5.2.0
      - charset-normalizer==3.2.0
      - click==8.1.7
      - cmake==3.25.0
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - contractions==0.1.73
      - cython==3.0.2
      - datasets==2.2.1
      - decorator==5.1.1
      - dill==0.3.7
      - docformatter==1.4
      - docutils==0.15.2
      - emoji==2.8.0
      - exceptiongroup==1.1.3
      - executing==1.2.0
      - fairscale==0.4.13
      - fairseq==0.12.2
      - filelock==3.9.0
      - fire==0.5.0
      - flake8==6.1.0
      - flake8-bugbear==23.9.16
      - frozenlist==1.4.0
      - fsspec==2022.2.0
      - fuzzywuzzy==0.18.0
      - gitdb==4.0.10
      - gitdb2==4.0.2
      - gitpython==3.1.37
      - google==3.0.0
      - google-api-core==2.11.0
      - google-auth==2.23.2
      - google-cloud-core==2.3.3
      - google-cloud-storage==2.11.0
      - google-crc32c==1.5.0
      - google-resumable-media==2.6.0
      - googleapis-common-protos==1.60.0
      - html2text==2020.1.16
      - html5lib==1.1
      - huggingface-hub==0.17.3
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - idna==3.4
      - imagesize==1.4.1
      - iniconfig==2.0.0
      - iopath==0.1.10
      - ipython==8.15.0
      - jedi==0.19.0
      - jinja2==3.1.2
      - joblib==1.3.2
      - jsonlines==4.0.0
      - lit==15.0.7
      - lxml==4.9.3
      - markdown==3.3.2
      - markdown-it-py==2.2.0
      - markupsafe==2.1.2
      - matplotlib-inline==0.1.6
      - mccabe==0.7.0
      - mdit-py-plugins==0.3.5
      - mdurl==0.1.2
      - mock==5.1.0
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiprocess==0.70.15
      - myst-parser==0.19.2
      - networkx==3.0
      - ninja==1.10.2.4
      - nltk==3.8.1
      - numpy==1.23.5
      - omegaconf==2.3.0
      - openai==0.27.7
      - packaging==23.1
      - pandas==2.1.1
      - parlai==1.7.2
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.0.1
      - pluggy==1.3.0
      - portalocker==2.8.2
      - prompt-toolkit==3.0.39
      - protobuf==3.20.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-gfm==2.0.0
      - py-rouge==1.1
      - pyahocorasick==2.0.0
      - pyarrow==13.0.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycodestyle==2.11.0
      - pycparser==2.21
      - pyflakes==3.1.0
      - pygments==2.16.1
      - pytest==7.4.2
      - pytest-datadir==1.4.1
      - pytest-regressions==2.5.0
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - regex==2023.8.8
      - requests==2.31.0
      - requests-mock==1.11.0
      - responses==0.18.0
      - rich==13.5.3
      - rsa==4.9
      - sacrebleu==2.3.1
      - safetensors==0.3.3
      - scikit-learn==1.3.1
      - scipy==1.11.3
      - sh==2.0.6
      - six==1.16.0
      - smmap==5.0.1
      - snowballstemmer==2.2.0
      - soupsieve==2.5
      - sphinx==5.1.1
      - sphinx-autodoc-typehints==1.10.3
      - sphinx-rtd-theme==1.3.0
      - sphinxcontrib-applehelp==1.0.7
      - sphinxcontrib-devhelp==1.0.5
      - sphinxcontrib-htmlhelp==2.0.4
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.6
      - sphinxcontrib-serializinghtml==1.1.9
      - stack-data==0.6.2
      - subword-nmt==0.3.8
      - sympy==1.12
      - tabulate==0.9.0
      - tensorboardx==2.5
      - termcolor==2.3.0
      - textsearch==0.0.24
      - threadpoolctl==3.2.0
      - tiktoken==0.5.1
      - tokenizers==0.13.3
      - tomli==2.0.1
      - torch==2.0.1+cu118
      - torchaudio==2.0.2
      - torchdata==0.6.1
      - torchtext==0.15.2
      - torchvision==0.15.2
      - tornado==6.3.3
      - tqdm==4.62.3
      - traitlets==5.10.1
      - transformers==4.33.3
      - triton==2.0.0
      - typing-extensions==4.4.0
      - tzdata==2023.3
      - unidecode==1.3.7
      - untokenize==0.1.1
      - urllib3==1.26.16
      - wcwidth==0.2.7
      - webencodings==0.5.1
      - websocket-client==1.6.3
      - whoosh==2.7.4
      - xxhash==3.3.0
      - yarl==1.9.2
